
# This is a template Makefile generated by rpcgen

# Parameters

CLIENT = trabalho_EduP_CLB_client
SERVER = trabalho_EduP_CLB_server

SOURCES_CLNT.c = 
SOURCES_CLNT.h = 
SOURCES_SVC.c = 
SOURCES_SVC.h = 
SOURCES.x = trabalho_EduP_CLB.x

TARGETS_SVC.c = trabalho_EduP_CLB_svc.c trabalho_EduP_CLB_server.c trabalho_EduP_CLB_xdr.c 
TARGETS_CLNT.c = trabalho_EduP_CLB_clnt.c trabalho_EduP_CLB_client.c trabalho_EduP_CLB_xdr.c 
TARGETS = trabalho_EduP_CLB.h trabalho_EduP_CLB_xdr.c trabalho_EduP_CLB_clnt.c trabalho_EduP_CLB_svc.c trabalho_EduP_CLB_client.c trabalho_EduP_CLB_server.c

OBJECTS_CLNT = $(SOURCES_CLNT.c:%.c=%.o) $(TARGETS_CLNT.c:%.c=%.o)
OBJECTS_SVC = $(SOURCES_SVC.c:%.c=%.o) $(TARGETS_SVC.c:%.c=%.o)
# Compiler flags 

CFLAGS += -g 
LDLIBS += -lnsl
RPCGENFLAGS = 

# Targets 

all : $(CLIENT) $(SERVER)

$(TARGETS) : $(SOURCES.x) 
	rpcgen $(RPCGENFLAGS) $(SOURCES.x)

$(OBJECTS_CLNT) : $(SOURCES_CLNT.c) $(SOURCES_CLNT.h) $(TARGETS_CLNT.c) 

$(OBJECTS_SVC) : $(SOURCES_SVC.c) $(SOURCES_SVC.h) $(TARGETS_SVC.c) 

$(CLIENT) : $(OBJECTS_CLNT) 
	$(LINK.c) -o $(CLIENT) $(OBJECTS_CLNT) $(LDLIBS) 

$(SERVER) : $(OBJECTS_SVC) 
	$(LINK.c) -o $(SERVER) $(OBJECTS_SVC) $(LDLIBS)

 clean:
	 $(RM) core $(TARGETS) $(OBJECTS_CLNT) $(OBJECTS_SVC) $(CLIENT) $(SERVER)

