/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

int contador_id=0;
int contaassinatura=0;


struct Contas {
	int numconta;
	int saldo;
};

#include "trabalho_EduP_CLB.h"



struct infos conta[100];

int cont = 0;

int *
deposito_100_svc(infos *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */
	 int i=0;
	 printf("valor: %s\n", argp->valor);
	 printf("valor: %s\n", argp->id);
	 //for(i=0; i<100; i++){
		//if(conta[i].id == argp->id){
			//printf("valor: %d\n", argp->valor);
			//conta[i].valor = conta[i].valor + argp->valor;
			//result = conta[i].valor;
		//}
	 //}

	return &result;
}

int *
saque_100_svc(infos *argp, struct svc_req *rqstp)
{
	static int  result=0;

	/*
	 * insert server code here
	 */
	 int i=0;
	 for(i=0; i<100; i++){
		if(conta[i].id == argp->id){
			conta[i].valor = conta[i].valor - argp->valor;
			result = conta[i].valor;
		}
	 }

	return &result;
}

int *
saldo_100_svc(infos *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */
	 int i=0;
	 for(i=0; i<100; i++){
		if(conta[i].id == argp->id){
			result = conta[i].valor;
		}
	 }

	return &result;
}

int *
aberturaconta_100_svc(infos *argp, struct svc_req *rqstp)
{
	static int  result=0;

	/*
	 * insert server code here
	 */
	conta[cont].id = cont;
	result = conta[cont].id ;
	cont++;
	return &result;
}

int *
fechamentoconta_100_svc(infos *argp, struct svc_req *rqstp)
{
	static int  result=0;

	/*
	 * insert server code here
	 */
	 int i=0;
	 for(i=0; i<100; i++){
		if(conta[i].id == argp->id){
			result = conta[i].id;
			conta[i].id = -1;
		}
	 }
	 
	return &result;
}

int *
autenticaconta_100_svc(infos *argp, struct svc_req *rqstp)
{
	static int  result=0;

	/*
	 * insert server code here
	 */
	 int i=0;
	 for(i=0; i<100; i++){
		if(conta[i].id == argp->id){
			result = 1;
		}
	 }

	return &result;
}

int *
retornaproxassinatura_100_svc(void *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}

int *
deposito_comfalha_100_svc(infos *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}
