/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

int contador_id=0;
int contaassinatura=0;


#include "trabalho_EduP_CLB.h"



struct infos conta[100];

int *
deposito_100_svc(infos *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */
	 int i=0;
	 
	 printf("o id da conta eh: %d\n", argp->id);
	 printf("o valor eh da conta eh: %d\n", argp->valor);
	 /*for(i=0; i<100; i++){
		if(conta[i].id == argp->id){
			conta[i].valor = conta[i].valor + argp->valor;
			result = 1;
		}
	 }*/

	return &result;
}

int *
saque_100_svc(infos *argp, struct svc_req *rqstp)
{
	static int  result=0;

	/*
	 * insert server code here
	 */
	 int i=0;
	 for(i=0; i<100; i++){
		if(conta[i].id == argp->id){
			conta[i].valor = conta[i].valor - argp->valor;
			result = 1;
		}
	 }

	return &result;
}

int *
saldo_100_svc(infos *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */
	 int i=0;
	 for(i=0; i<100; i++){
		if(conta[i].id == argp->id){
			result = conta[i].valor;
		}
	 }

	return &result;
}

int *
aberturaconta_100_svc(infos *argp, struct svc_req *rqstp)
{
	static int  result=0;

	/*
	 * insert server code here
	 */
	 printf("Requisição para abertura de conta\n");
	 if (argp->num_assinatura == contaassinatura){
		contador_id++; // começa em '1' (Não queremos conta n '0')
		conta[contador_id].id = contador_id;
		result = conta[contador_id].id ;
	}
	return &result;
}

int *
fechamentoconta_100_svc(infos *argp, struct svc_req *rqstp)
{
	static int  result=0;

	/*
	 * insert server code here
	 */
	 printf("Requisição para fechamento da conta %d\n",argp->id);
	 for(int i=0; i<100; i++){
		if(conta[i].id == argp->id){
			conta[i].id = 0;
			result = 1;
			break;
		}
	 }
	 
	return &result;
}

int *
autenticaconta_100_svc(infos *argp, struct svc_req *rqstp)
{
	static int  result;

	printf("Requisição para autenticação da conta %d\n",argp->id);	
	/*
	 * insert server code here
	 */
	 result=0;
	 for(int i=0; i<=contador_id; i++){
	//	 printf("DEBUG Autentica: i=%d / conta[i].id=%d argp->id=%d\n",i,conta[i].id,argp->id);
		if(conta[i].id == argp->id){
			result = 1;
			break;
		}
	 }
	
	return &result;
}

int *
retornaproxassinatura_100_svc(void *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */
	contaassinatura++;
	result=contaassinatura;
	printf("Requisição de chave número %d\n",result);
	
	return &result;
}

int *
deposito_comfalha_100_svc(infos *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}
