/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _TRABALHO_EDUP_CLB_H_RPCGEN
#define _TRABALHO_EDUP_CLB_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct infos {
	int id;
	int valor;
	int num_assinatura;
};
typedef struct infos infos;

#define PROG 55555555
#define VERSAO 100

#if defined(__STDC__) || defined(__cplusplus)
#define deposito 1
extern  int * deposito_100(infos *, CLIENT *);
extern  int * deposito_100_svc(infos *, struct svc_req *);
#define saque 2
extern  int * saque_100(infos *, CLIENT *);
extern  int * saque_100_svc(infos *, struct svc_req *);
#define saldo 3
extern  int * saldo_100(infos *, CLIENT *);
extern  int * saldo_100_svc(infos *, struct svc_req *);
#define aberturaConta 4
extern  int * aberturaconta_100(infos *, CLIENT *);
extern  int * aberturaconta_100_svc(infos *, struct svc_req *);
#define fechamentoConta 5
extern  int * fechamentoconta_100(infos *, CLIENT *);
extern  int * fechamentoconta_100_svc(infos *, struct svc_req *);
#define autenticaConta 6
extern  int * autenticaconta_100(infos *, CLIENT *);
extern  int * autenticaconta_100_svc(infos *, struct svc_req *);
#define retornaProxAssinatura 7
extern  int * retornaproxassinatura_100(void *, CLIENT *);
extern  int * retornaproxassinatura_100_svc(void *, struct svc_req *);
#define deposito_comFalha 8
extern  int * deposito_comfalha_100(infos *, CLIENT *);
extern  int * deposito_comfalha_100_svc(infos *, struct svc_req *);
extern int prog_100_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define deposito 1
extern  int * deposito_100();
extern  int * deposito_100_svc();
#define saque 2
extern  int * saque_100();
extern  int * saque_100_svc();
#define saldo 3
extern  int * saldo_100();
extern  int * saldo_100_svc();
#define aberturaConta 4
extern  int * aberturaconta_100();
extern  int * aberturaconta_100_svc();
#define fechamentoConta 5
extern  int * fechamentoconta_100();
extern  int * fechamentoconta_100_svc();
#define autenticaConta 6
extern  int * autenticaconta_100();
extern  int * autenticaconta_100_svc();
#define retornaProxAssinatura 7
extern  int * retornaproxassinatura_100();
extern  int * retornaproxassinatura_100_svc();
#define deposito_comFalha 8
extern  int * deposito_comfalha_100();
extern  int * deposito_comfalha_100_svc();
extern int prog_100_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_infos (XDR *, infos*);

#else /* K&R C */
extern bool_t xdr_infos ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_TRABALHO_EDUP_CLB_H_RPCGEN */
