/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "trabalho_EduP_CLB.h"

bool_t
xdr_infos (XDR *xdrs, infos *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->id))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->valor))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->num_assinatura))
		 return FALSE;
	return TRUE;
}
