/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "trabalho_EduP_CLB.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

static void
prog_100(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		infos deposito_100_arg;
		infos saque_100_arg;
		infos saldo_100_arg;
		infos aberturaconta_100_arg;
		infos fechamentoconta_100_arg;
		infos autenticaconta_100_arg;
		infos deposito_comfalha_100_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case deposito:
		_xdr_argument = (xdrproc_t) xdr_infos;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) deposito_100_svc;
		break;

	case saque:
		_xdr_argument = (xdrproc_t) xdr_infos;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) saque_100_svc;
		break;

	case saldo:
		_xdr_argument = (xdrproc_t) xdr_infos;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) saldo_100_svc;
		break;

	case aberturaConta:
		_xdr_argument = (xdrproc_t) xdr_infos;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) aberturaconta_100_svc;
		break;

	case fechamentoConta:
		_xdr_argument = (xdrproc_t) xdr_infos;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) fechamentoconta_100_svc;
		break;

	case autenticaConta:
		_xdr_argument = (xdrproc_t) xdr_infos;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) autenticaconta_100_svc;
		break;

	case retornaProxAssinatura:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) retornaproxassinatura_100_svc;
		break;

	case deposito_comFalha:
		_xdr_argument = (xdrproc_t) xdr_infos;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) deposito_comfalha_100_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

int
main (int argc, char **argv)
{
	register SVCXPRT *transp;

	pmap_unset (PROG, VERSAO);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, PROG, VERSAO, prog_100, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (PROG, VERSAO, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, PROG, VERSAO, prog_100, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (PROG, VERSAO, tcp).");
		exit(1);
	}

	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
